services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .                        
      dockerfile: docker/web/Dockerfile 
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

  nginx:
    build:
      context: .                     
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/vol/static
      - media_volume:/vol/media

volumes:
  postgres_data:
  static_volume:
  media_volume:
